// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz1J0udMIL2jzgnRZ9qOPTTc2SNkg8Ayo',
    appId: '1:985131110861:web:8c5fa81220dd0ecdb33484',
    messagingSenderId: '985131110861',
    projectId: 'fstore-bda14',
    authDomain: 'fstore-bda14.firebaseapp.com',
    storageBucket: 'fstore-bda14.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNA-QJYgJrNL4FV1dmDsol2TN8D4J0SjI',
    appId: '1:985131110861:android:92bdcfb47a3a2945b33484',
    messagingSenderId: '985131110861',
    projectId: 'fstore-bda14',
    storageBucket: 'fstore-bda14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwVxXyDheaV6vvPQapRPAQMwlYKOWvF4s',
    appId: '1:985131110861:ios:eaaae595b367ac7bb33484',
    messagingSenderId: '985131110861',
    projectId: 'fstore-bda14',
    storageBucket: 'fstore-bda14.appspot.com',
    iosClientId: '985131110861-06shr008ll3pd17fk68ngqf2a1n7qgd0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwVxXyDheaV6vvPQapRPAQMwlYKOWvF4s',
    appId: '1:985131110861:ios:eaaae595b367ac7bb33484',
    messagingSenderId: '985131110861',
    projectId: 'fstore-bda14',
    storageBucket: 'fstore-bda14.appspot.com',
    iosClientId: '985131110861-06shr008ll3pd17fk68ngqf2a1n7qgd0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fstore',
  );
}
