// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDICbOqn8uKCT1CKXYCivhW6NtQN6Srjic',
    appId: '1:42779223890:web:2f39e051fb3f66f1f2fc8b',
    messagingSenderId: '42779223890',
    projectId: 'flutter2-b5a36',
    authDomain: 'flutter2-b5a36.firebaseapp.com',
    storageBucket: 'flutter2-b5a36.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7N4Mj_Dtqkqrzd15hDtQT8h6-ra3C6K4',
    appId: '1:42779223890:android:45c2f78701167beff2fc8b',
    messagingSenderId: '42779223890',
    projectId: 'flutter2-b5a36',
    storageBucket: 'flutter2-b5a36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQNVkiCEL82c4UcC7AnYO3dt8hvVU2bFI',
    appId: '1:42779223890:ios:5fcc995a0ce47107f2fc8b',
    messagingSenderId: '42779223890',
    projectId: 'flutter2-b5a36',
    storageBucket: 'flutter2-b5a36.appspot.com',
    iosClientId: '42779223890-7lmn41doaofd1g0qptehacv4c8nhjdra.apps.googleusercontent.com',
    iosBundleId: 'com.example.workWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQNVkiCEL82c4UcC7AnYO3dt8hvVU2bFI',
    appId: '1:42779223890:ios:5fcc995a0ce47107f2fc8b',
    messagingSenderId: '42779223890',
    projectId: 'flutter2-b5a36',
    storageBucket: 'flutter2-b5a36.appspot.com',
    iosClientId: '42779223890-7lmn41doaofd1g0qptehacv4c8nhjdra.apps.googleusercontent.com',
    iosBundleId: 'com.example.workWithFirebase',
  );
}
